### ISSUE TITLE
Working with Python 3.9?

### ISSUE THREAD

**Issue by edcloudcycle** [mysz/versionup#10]
Hi, 
I find versionner hangs on my Windows 10 system with python 3.9 installed. I noticed 3.9 is not in the list of supported versions,. is it known not to work?

```
Traceback (most recent call last):
  File "c:\users\ed\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ed\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ed\AppData\Local\Programs\Python\Python39\Scripts\ver.exe\__main__.py", line 7, in <module>
  File "c:\users\ed\appdata\local\programs\python\python39\lib\site-packages\versionner\cli.py", line 250, in main
    return execute(sys.argv[0], sys.argv[1:])
  File "c:\users\ed\appdata\local\programs\python\python39\lib\site-packages\versionner\cli.py", line 218, in execute
    proj_cfg_file = _find_project_config_file(cfg_files[0])
  File "c:\users\ed\appdata\local\programs\python\python39\lib\site-packages\versionner\cli.py", line 194, in _find_project_config_file
    proj_cfg_file = proj_cfg_dir / defaults.RC_FILENAME
  File "c:\users\ed\appdata\local\programs\python\python39\lib\pathlib.py", line 965, in __truediv__
    return self._make_child((key,))
  File "c:\users\ed\appdata\local\programs\python\python39\lib\pathlib.py", line 726, in _make_child
    drv, root, parts = self._parse_args(args)
  File "c:\users\ed\appdata\local\programs\python\python39\lib\pathlib.py", line 689, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "c:\users\ed\appdata\local\programs\python\python39\lib\pathlib.py", line 74, in parse_parts
    drv, root, rel = self.splitroot(part)
KeyboardInterrupt
```

Thanks

Ed

**Comment by msztolcman** [comment]
Hello,

3.9 is not on  the list only because of lack of other updates. I've tested it now in Python 3.9 and it works well. However, I am testing it on POSIX compatible OSes (linux, macos). It looks like your problem with hangs is related to windows rather then to Python version.

I'm not able to test it on Windows machine right now, will try in few days run something in virtualbox and then try to debug this issue.

Thank you for bug report!

**Comment by edcloudcycle** [comment]
Thanks, just let me know if there is anything I can do to help. I am using a venv in this folder if that makes any difference.

**Comment by msztolcman** [comment]
>  I am using a venv in this folder if that makes any difference.

It shouldn't - I am using it in virtualenvs all the time :) However, it's windows ;) Everything may happen ;) I will verify this too, thanks for update :)

**Comment by edcloudcycle** [comment]
Hi @msztolcman,
Did you have a chance to look a this? I will try again today.
Thanks
Ed

**Comment by edcloudcycle** [comment]
I still see the same problem even when powershell is admin.

**Comment by msztolcman** [comment]
Hi @edcloudcycle,

I've been too busy for few days unfortunately, deadlines in my dayjob :(
I've installed versionner on my win VM, and once I've even found it on a win machine, but then VM hangs, and after this I can't find a place where it's installed anymore :D I'm not a Windows-compatible guy, it's hard to use this ;)

I will retry maybe today evening ;)

**Comment by espetro** [comment]
@edcloudcycle did you try in WSL (1 or 2)?

**Comment by edcloudcycle** [comment]
No but that's a good idea

**Comment by espetro** [comment]
I'm using Python 3.9 in a MacOS setup and it works. If you can, use WSL as you're going to get the same behaviour we're getting.

**Comment by msztolcman** [comment]
Unfortunately it looks like I am not Windows compatible. Working on VM with Windows is hard and system still hangs. I have no standalone Windows computer available.
It's definitely Windows related. On POSIX or macOS everything works fine also on Python3.9. I have no way to debug the problem on Windows :( Maybe using this WSL will help, or maybe someone with Windows can debug this?
