### ISSUE TITLE
Error when tmp directory is in a different device (partition)

### ISSUE THREAD

**Issue by rlaverde** [mysz/versionup#4]
When running `$ ver init` it fails:
```
Traceback (most recent call last):
  File "/home/rlaverde/.local/bin/ver", line 11, in <module>
    sys.exit(main())
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/cli.py", line 251, in main
    return execute(sys.argv[0], sys.argv[1:])
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/cli.py", line 229, in execute
    result = cmd.execute()
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/commands/command.py", line 22, in execute
    return self.run()
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/commands/init.py", line 17, in run
    modified_files = save_version_and_update_files(self.cfg, version_file, current)
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/commands/files_management.py", line 91, in s_version_and_update_files
    version_file.write(version_to_save)
  File "/home/rlaverde/.local/lib/python3.5/site-packages/versionner/version.py", line 225, in write
    pathlib.Path(fh.name).rename(self._path)
  File "/usr/lib/python3.5/pathlib.py", line 1279, in rename
    self._accessor.rename(self, target)
  File "/usr/lib/python3.5/pathlib.py", line 377, in wrapped
    return strfunc(str(pathobjA), str(pathobjB), *args)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpqpdq9_le' -> '/home/rlaverde/code/spyder-reports/VERSION'
```

os.rename documentation: _"The operation may fail on some Unix flavors if src and dst are on different filesystems."_ https://docs.python.org/3/library/os.html#os.rename** 

workaround:

temporally change tmp directory

`export TMPDIR=~/tmp`

**Comment by msztolcman** [comment]
Hi @rlaverde, thanks for reporting this :)
I've submitted fix for this issue, so you can update versionner and everything should work better now :)
